import { VisualPersona, VisualPersonaId } from '../../types/presentation';
import { SlideTheme } from '../../types/slide';

export const VISUAL_PERSONAS: Record<VisualPersonaId, VisualPersona> = {
  'editorial-warm': {
    id: 'editorial-warm',
    personaId: 'editorial-warm',
    name: 'Editorial Warm',
    tagline: 'Literary linen, dark espresso & terracotta',
    vibe: 'Canva editorial, warm bookish tactile paper, serif headlines',
    description: 'Linen paper background with dark espresso typography and warm terracotta accents.',
    previewColors: ['#FBF8F3', '#1A1715', '#B85042', '#6E655F'],
    background: {
      type: 'color',
      color: '#FBF8F3',
    },
    primaryText: '#1A1715',
    secondaryText: '#6E655F',
    accent: '#B85042',
    cardBg: '#F5F0E8',
    cardBorder: '#E8E2D9',
    borderRadius: 12,
    dividerColor: '#E2DBD0',
    headingFont: 'Playfair Display',
    fontFamily: 'Inter',
  },

  'swiss-studio': {
    id: 'swiss-studio',
    personaId: 'swiss-studio',
    name: 'Swiss Studio',
    tagline: 'Clean chalk, jet black & Klein blue',
    vibe: 'Sharp 0px geometry, International Typographic Style, Grotesk + Mono',
    description: 'Clean chalk background with high-contrast jet black typography and electric Klein Blue accents.',
    previewColors: ['#F4F4F6', '#111111', '#0044EE', '#555555'],
    background: {
      type: 'color',
      color: '#F4F4F6',
    },
    primaryText: '#111111',
    secondaryText: '#555555',
    accent: '#0044EE',
    cardBg: '#E8E8EC',
    cardBorder: '#D0D0D8',
    borderRadius: 0,
    dividerColor: '#111111',
    headingFont: 'Space Grotesk',
    fontFamily: 'Fira Code',
  },

  'earthy-craft': {
    id: 'earthy-craft',
    personaId: 'earthy-craft',
    name: 'Earthy Craft',
    tagline: 'Sage gray paper, deep pine & warm amber',
    vibe: 'Calm botanical craft, organic studio feel, humanist editorial',
    description: 'Sage gray background with deep forest pine typography and warm amber ochre highlights.',
    previewColors: ['#EBEFE9', '#182B21', '#D9822B', '#4D5D53'],
    background: {
      type: 'color',
      color: '#EBEFE9',
    },
    primaryText: '#182B21',
    secondaryText: '#4D5D53',
    accent: '#D9822B',
    cardBg: '#DFE6DC',
    cardBorder: '#CCD6C8',
    borderRadius: 16,
    dividerColor: '#C4D1BF',
    headingFont: 'Playfair Display',
    fontFamily: 'Plus Jakarta Sans',
  },

  'moody-editorial': {
    id: 'moody-editorial',
    personaId: 'moody-editorial',
    name: 'Moody Editorial',
    tagline: 'Deep obsidian, cream chalk & warm gold',
    vibe: 'High-end editorial magazine, luxury cinematic dark mode',
    description: 'Deep obsidian charcoal with warm cream typography and rich amber-gold accents.',
    previewColors: ['#121316', '#F5F0E6', '#E5A952', '#A8A29E'],
    background: {
      type: 'color',
      color: '#121316',
    },
    primaryText: '#F5F0E6',
    secondaryText: '#A8A29E',
    accent: '#E5A952',
    cardBg: '#1B1C22',
    cardBorder: '#2E303A',
    borderRadius: 16,
    dividerColor: '#2E303A',
    headingFont: 'Playfair Display',
    fontFamily: 'Inter',
  },
};

export const PERSONA_LIST: VisualPersona[] = Object.values(VISUAL_PERSONAS);

/**
 * 10 Authentic Canva Deck Themes extracted from /canva-samples
 */
export const CANVA_DECK_THEMES: SlideTheme[] = [
  {
    id: 'canva-theme-blue-black-minimal',
    name: 'Canva Blue & Black Minimalist',
    description: 'Extracted from Blue and Black Minimalist Business Presentation',
    previewColors: ['#F4F7FB', '#0A192F', '#1E40AF', '#64748B'],
    background: {
      type: 'color',
      color: '#F4F7FB',
    },
    primaryText: '#0A192F',
    secondaryText: '#64748B',
    accent: '#1E40AF',
    cardBg: '#FFFFFF',
    cardBorder: '#E2E8F0',
    fontFamily: 'Inter',
    headingFont: 'Outfit',
  },
  {
    id: 'canva-theme-blue-bold-proposal',
    name: 'Canva Blue Bold Proposal',
    description: 'Extracted from Blue Bold Project Proposal Presentation',
    previewColors: ['#0F172A', '#FFFFFF', '#3B82F6', '#94A3B8'],
    background: {
      type: 'color',
      color: '#0F172A',
    },
    primaryText: '#FFFFFF',
    secondaryText: '#94A3B8',
    accent: '#3B82F6',
    cardBg: '#1E293B',
    cardBorder: '#334155',
    fontFamily: 'Inter',
    headingFont: 'Space Grotesk',
  },
  {
    id: 'canva-theme-blue-modern-pitch',
    name: 'Canva Modern Business Pitch',
    description: 'Extracted from Blue Modern Business Pitch Deck Presentation',
    previewColors: ['#F8FAFC', '#0F172A', '#0284C7', '#475569'],
    background: {
      type: 'color',
      color: '#F8FAFC',
    },
    primaryText: '#0F172A',
    secondaryText: '#475569',
    accent: '#0284C7',
    cardBg: '#FFFFFF',
    cardBorder: '#E2E8F0',
    fontFamily: 'Inter',
    headingFont: 'Plus Jakarta Sans',
  },
  {
    id: 'canva-theme-cybersecurity-green',
    name: 'Canva Cybersecurity Matrix',
    description: 'Extracted from Cybersecurity Roadmap Illustrative Green Presentation',
    previewColors: ['#0A192F', '#F8FAFC', '#00FF66', '#64FFDA'],
    background: {
      type: 'color',
      color: '#0A192F',
    },
    primaryText: '#F8FAFC',
    secondaryText: '#8892B0',
    accent: '#00FF66',
    cardBg: '#112240',
    cardBorder: '#233554',
    fontFamily: 'Fira Code',
    headingFont: 'Space Grotesk',
  },
  {
    id: 'canva-theme-dark-blue-gradient',
    name: 'Canva Dark Indigo Gradient',
    description: 'Extracted from Dark Blue Gradient Modern Professional Presentation',
    previewColors: ['#0B132B', '#1C2541', '#5BC0BE', '#F8FAFC'],
    background: {
      type: 'gradient',
      gradient: {
        from: '#0B132B',
        to: '#1C2541',
        direction: 'to-br',
      },
    },
    primaryText: '#F8FAFC',
    secondaryText: '#A5B4FC',
    accent: '#5BC0BE',
    cardBg: '#1C2541',
    cardBorder: '#3A506B',
    fontFamily: 'Inter',
    headingFont: 'Outfit',
  },
  {
    id: 'canva-theme-fintech-evolution',
    name: 'Canva Fintech Evolution',
    description: 'Extracted from Green and Black Modern Fintech Evolution Presentation',
    previewColors: ['#0A0A0A', '#F4F4F6', '#00E676', '#71717A'],
    background: {
      type: 'color',
      color: '#0A0A0A',
    },
    primaryText: '#F4F4F6',
    secondaryText: '#A1A1AA',
    accent: '#00E676',
    cardBg: '#18181B',
    cardBorder: '#27272A',
    fontFamily: 'Inter',
    headingFont: 'Space Grotesk',
  },
  {
    id: 'canva-theme-modern-biotech',
    name: 'Canva Modern Biotechnology',
    description: 'Extracted from Green and White Modern Biotechnology Presentation',
    previewColors: ['#F0FDF4', '#14532D', '#22C55E', '#4B5563'],
    background: {
      type: 'color',
      color: '#F0FDF4',
    },
    primaryText: '#14532D',
    secondaryText: '#4B5563',
    accent: '#22C55E',
    cardBg: '#FFFFFF',
    cardBorder: '#DCFCE7',
    fontFamily: 'Inter',
    headingFont: 'Plus Jakarta Sans',
  },
  {
    id: 'canva-theme-grey-bold-minimal',
    name: 'Canva Grey Architectural',
    description: 'Extracted from Grey Bold Minimalist Project Proposal Presentation',
    previewColors: ['#F0F5F9', '#1E2022', '#52616B', '#686D76'],
    background: {
      type: 'color',
      color: '#F0F5F9',
    },
    primaryText: '#1E2022',
    secondaryText: '#686D76',
    accent: '#52616B',
    cardBg: '#FFFFFF',
    cardBorder: '#C9D6DF',
    fontFamily: 'Inter',
    headingFont: 'Bricolage Grotesque',
  },
  {
    id: 'canva-theme-red-beige-pitch',
    name: 'Canva Crimson & Sand Pitch',
    description: 'Extracted from Red and Beige Bold Modern Professional Business Pitch Deck Presentation',
    previewColors: ['#F5EBE0', '#3F0C10', '#C1121F', '#780000'],
    background: {
      type: 'color',
      color: '#F5EBE0',
    },
    primaryText: '#3F0C10',
    secondaryText: '#6E655F',
    accent: '#C1121F',
    cardBg: '#EDE0D4',
    cardBorder: '#E6CCB2',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Playfair Display',
  },
  {
    id: 'canva-theme-red-black-cyber',
    name: 'Canva Red & Black Cyber',
    description: 'Extracted from Red and Black Modern Clean Cyber Security Presentation',
    previewColors: ['#0D0D0D', '#F1FAEE', '#E63946', '#457B9D'],
    background: {
      type: 'color',
      color: '#0D0D0D',
    },
    primaryText: '#F1FAEE',
    secondaryText: '#94A3B8',
    accent: '#E63946',
    cardBg: '#1A1A1A',
    cardBorder: '#2E2E2E',
    fontFamily: 'Fira Code',
    headingFont: 'Space Grotesk',
  },
];

export function getPersonaById(id: string): VisualPersona {
  return VISUAL_PERSONAS[id as VisualPersonaId] || VISUAL_PERSONAS['editorial-warm'];
}
